### ISSUE TITLE
Laggy Scrolling

### ISSUE THREAD

**Issue by jzanecook** [KBVE/kbve.com#41]
**Describe the bug**
Scrolling on the page is laggy and has dropped frames.

* * *

**To Reproduce**

1. Go to 'https://kbve.com'
2. Click on 'literally anything'
3. Scroll down to 'literally anywhere'

* * *

**Expected behavior**
Scroll fast

* * *

**Screenshots**
![image](https://user-images.githubusercontent.com/90814067/191141609-b4fba9c4-fc09-4de3-b763-9948b56fa44b.png)

* * *

**Desktop:**

- OS: Windows 11
- Browser: Chrome
- Version: 105.0.5195.127 

* * *

**Comment by h0lybyte** [comment]
Could be caused by the scrolling? Reference to this stackoverflow below
[1] - https://stackoverflow.com/questions/62883780/how-to-reduce-fps-drops-in-javascript-scroll-css-transitions

* * *

Or it could be the opacity?
[2] https://stackoverflow.com/questions/66885367/interpreting-dropped-frame-in-chrome-dev-tools

**Comment by jzanecook** [comment]
I removed (e.g. commented out) any reference to the blur filter in all scss files and it fixed it, except the main page seems a little off still. Should be good for now, though, and the transparency still looks nice even without the blur. It's possible that it was off purely because of the 80px.
